name: Test

on:
  pull_request:
    branches: 
      - main

jobs:
  Train:
    uses: ./.github/workflows/train.yml
    secrets: inherit

  pull_and_test:
    name: pull_and_test
    needs: [Train]
    runs-on: ubuntu-latest
    steps:
      - name: Pull Docker Image
        run: docker pull cmsanchi/ci_cd_assignment:v1
      
      - name: Run Tests
        run: |
          OUTPUT=$(docker run --rm cmsanchi/ci_cd_assignment:v1)
          echo "Score:"
          echo "$OUTPUT"
          if [[ `echo "$OUTPUT 0.50" | awk '{print ($1 < $2)}'` == 1 ]]; then 
            echo "Insufficient Accuracy" && exit 1
          fi
