name: Test

on:
  workflow_run:
    workflows: ["Train"]
    types: [completed]

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Pull Docker Image
        run: docker pull cmsanchi/cicd_assignment:latest

      - name: Run tests in Docker container
        run: |
          OUTPUT=$(docker run --rm cmsanchi/cicd_assignment:latest python test.py)
          echo "Score: $OUTPUT"
          if [ $(echo "$OUTPUT > 0.50" | bc) -eq 1 ]; then
            echo "Test Passed"
          else
            echo "Test Failed"
            exit 1
          fi
