name: Test

on:
  pull_request:
    branches: [ "main" ]
  workflow_run:
    workflows: ["Train"]
    types: [completed]    

jobs:
  pull_and_test:
    name: Pull Docker Image and Test
    runs-on: ubuntu-latest
    needs: build_and_push
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Pull Docker Image
        run: docker pull cmsanchi/ci_cd_assignment:v1

      - name: Run Tests
        run: |
          OUTPUT=$(docker run --rm cmsanchi/ci_cd_assignment:v1 python test.py)
          echo "Score:"
          echo "$OUTPUT"
          if [[ `echo "$OUTPUT > 0.50" | bc` -eq 1 ]]; then
            echo "Test Passed"
          else
            echo "Test Failed"
            exit 1
          fi
