name: Test

on:
  pull_request:
    branches:
      - main

jobs:
  test-score:
    runs-on: ubuntu-latest
    needs: build-and-push
    
    steps:
      - name: Pull Docker Image
        run: docker pull ${{ secrets.DOCKERHUB_USERNAME }}/cicd-assignment:latest
        
      - name: Run Docker Image and Test
        run: |
          docker run ${{ secrets.DOCKERHUB_USERNAME }}/cicd-assignment:latest python test.py
