name: Train

on: [workflow_call]

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build and Push Docker Image
        run: |
          docker build --file Dockerfile --tag cmsanchi/ci_cd_assignment:v1 .
          docker push cmsanchi/ci_cd_assignment:v1
